const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'时间未记录';const rating=r=>({again:'没想起来',hard:'很吃力',good:'基本掌握',easy:'很熟练'}[r]||r);let d,role,selected;
async function get(url){const r=await fetch(url);if(r.status===401){location.replace('/login');throw new Error('需要登录');}if(!r.ok)throw new Error('数据读取失败');return r.json();}
async function load(){d=await get('/api/calendar?month='+$('#month').value);selected=selected?.startsWith(d.month)?selected:d.today.startsWith(d.month)?d.today:d.month+'-01';render();}
function items(points){const q=$('#search').value.trim();const rows=points.filter(p=>!q||[p.title,p.source].join(' ').includes(q));return rows.map(p=>`<div class="calendar-item"><div><strong>${esc(p.title)}</strong><small>${esc(p.source)} · 原定 ${esc(p.due)} · ${({learn:'首次复习',forgotten:'发现遗忘',review:'间隔复习'})[p.kind]}</small></div>${role==='learner'?`<a class="button" href="/study?point=${encodeURIComponent(p.id)}">开始回忆</a>`:'<span>管理员查看</span>'}</div>`).join('')||'<p class="empty">没有匹配的知识点</p>';}
function render(){const [year,month]=d.month.split('-').map(Number),first=new Date(Date.UTC(year,month-1,1)).getUTCDay(),count=new Date(Date.UTC(year,month,0)).getUTCDate();$('#calendar').innerHTML=['日','一','二','三','四','五','六'].map(s=>`<span>周${s}</span>`).join('')+'<span></span>'.repeat(first)+Array.from({length:count},(_,i)=>{const day=d.month+'-'+String(i+1).padStart(2,'0'),due=d.points.filter(p=>p.due===day).length,done=d.records.filter(r=>r.reviewedOn===day).length;return `<button data-day="${day}" class="${day===selected?'selected':''}"><strong>${i+1}</strong><small>${due?'待复习 '+due:''}${done?' 完成 '+done+' 次':''}</small></button>`;}).join('');$('#day-heading').textContent=selected+' · 复习安排';$('#day-items').innerHTML=items(d.points.filter(p=>p.due===selected));$('#overdue').innerHTML=items(d.overdue);$('#record-list').innerHTML=d.records.map(r=>`<button class="calendar-item" data-record="${esc(r.id)}"><strong>${esc(r.title)}</strong><small>${esc(r.reviewedOn)} · ${rating(r.rating)} · 下次 ${esc(r.nextReviewOn)}</small></button>`).join('')||'<p class="empty">本月没有真实自评记录</p>';}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.day){selected=b.dataset.day;render();$('#day-heading').scrollIntoView({block:'start',behavior:'smooth'});}if(b.dataset.record){const r=d.records.find(r=>r.id===b.dataset.record);$('#record-body').innerHTML=`<h2>${esc(r.title)}</h2><p>${rating(r.rating)} · ${date(r.reviewedAt)}</p><p>当次下次日期 ${esc(r.nextReviewOn)}<br>当前排程 ${esc(r.currentState?.nextReviewOn||'未记录')}</p><h3>本人答案</h3><pre>${esc(r.attempt?.content||'历史答案未精确关联')}</pre><h3>当时题目</h3><pre>${esc(r.attempt?.taskSnapshot?.prompt||'未记录')}</pre><h3>反馈</h3>${r.feedback.map(f=>`<p>${esc(f.status)}</p><pre>${esc(f.feedback||f.errorCode||'未返回')}</pre>`).join('')||'<p>未关联</p>'}`;$('#record-detail').showModal();}});
$('#close').onclick=()=>$('#record-detail').close();$('#search').oninput=()=>render();$('#month').onchange=()=>load();function shift(amount){const [y,m]=$('#month').value.split('-').map(Number);$('#month').value=new Date(Date.UTC(y,m-1+amount,1)).toISOString().slice(0,7);load();}$('#previous').onclick=()=>shift(-1);$('#next').onclick=()=>shift(1);$('#today').onclick=()=>{$('#month').value=d.today.slice(0,7);load();};
try{role=(await get('/api/session')).role;const init=await get('/api/calendar');$('#month').value=init.month;await load();}catch(e){$('#day-items').textContent=e.message;}
