
PRAGMA foreign_keys=ON;
CREATE TABLE schema_migrations(version INTEGER PRIMARY KEY, name TEXT NOT NULL, applied_at TEXT NOT NULL);
CREATE TABLE people(id TEXT PRIMARY KEY, display_name TEXT NOT NULL, role TEXT NOT NULL UNIQUE CHECK(role IN ('learner','admin')));
CREATE TABLE channel_identities(id TEXT PRIMARY KEY, person_id TEXT NOT NULL REFERENCES people(id), app_id TEXT NOT NULL, channel TEXT NOT NULL, external_id TEXT NOT NULL, UNIQUE(app_id,channel,external_id));
CREATE TABLE role_bindings(person_id TEXT PRIMARY KEY REFERENCES people(id), role TEXT NOT NULL, source TEXT NOT NULL, captured_at TEXT NOT NULL);
CREATE TABLE identity_observations(id TEXT PRIMARY KEY, person_id TEXT REFERENCES people(id), scope_id TEXT, label TEXT, evidence_kind TEXT NOT NULL, observed_at TEXT, imported_at TEXT NOT NULL, snapshot_json TEXT NOT NULL);
CREATE TABLE identity_change_events(id TEXT PRIMARY KEY, person_id TEXT REFERENCES people(id), field TEXT NOT NULL, old_value TEXT, new_value TEXT, source_event_id TEXT, occurred_at TEXT);
CREATE TABLE learner_profiles(person_id TEXT PRIMARY KEY REFERENCES people(id), exam_goal TEXT, study_stage TEXT, daily_minutes INTEGER, version TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE profile_change_events(id TEXT PRIMARY KEY, person_id TEXT NOT NULL REFERENCES people(id), field TEXT NOT NULL, occurred_at TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE conversation_scopes(id TEXT PRIMARY KEY, app_id TEXT, channel TEXT, chat_type TEXT, chat_id TEXT, peer_id TEXT, thread_id TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE conversation_sessions(id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES conversation_scopes(id), created_at TEXT, archived_at TEXT, is_current INTEGER NOT NULL, snapshot_json TEXT NOT NULL);
CREATE TABLE conversation_events(id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES conversation_sessions(id), ordinal INTEGER NOT NULL, event_type TEXT NOT NULL, source_event_id TEXT, sender_id TEXT, text TEXT, assistant_text TEXT, occurred_at TEXT, snapshot_json TEXT NOT NULL, UNIQUE(session_id,ordinal));
CREATE INDEX conversation_events_session_time ON conversation_events(session_id,occurred_at);
CREATE TABLE memory_notes(id TEXT PRIMARY KEY, scope_id TEXT NOT NULL REFERENCES conversation_scopes(id), text TEXT NOT NULL, source_id TEXT, status TEXT NOT NULL, created_at TEXT);
CREATE TABLE memory_note_versions(id TEXT PRIMARY KEY, note_id TEXT NOT NULL REFERENCES memory_notes(id), version INTEGER NOT NULL, text TEXT NOT NULL, occurred_at TEXT, snapshot_json TEXT NOT NULL, UNIQUE(note_id,version));
CREATE TABLE knowledge_sources(id TEXT PRIMARY KEY, scope_id TEXT REFERENCES conversation_scopes(id), title TEXT, current_version INTEGER, created_at TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE knowledge_revisions(id TEXT PRIMARY KEY, source_id TEXT NOT NULL REFERENCES knowledge_sources(id), version INTEGER NOT NULL, occurred_at TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE source_pages(id TEXT PRIMARY KEY, source_id TEXT REFERENCES knowledge_sources(id), page_number INTEGER, asset_id TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE knowledge_points(id TEXT PRIMARY KEY, source_id TEXT REFERENCES knowledge_sources(id), scope_id TEXT REFERENCES conversation_scopes(id), title TEXT NOT NULL, body TEXT, source_version INTEGER, uploaded_at TEXT, forgotten_on TEXT, hidden INTEGER NOT NULL, origin_status TEXT NOT NULL, snapshot_json TEXT NOT NULL);
CREATE INDEX knowledge_points_scope ON knowledge_points(scope_id,uploaded_at);
CREATE TABLE knowledge_relations(id TEXT PRIMARY KEY, from_point_id TEXT NOT NULL REFERENCES knowledge_points(id), to_point_id TEXT NOT NULL REFERENCES knowledge_points(id), relation TEXT NOT NULL, snapshot_json TEXT NOT NULL);
CREATE TABLE assets(id TEXT PRIMARY KEY, relative_path TEXT NOT NULL UNIQUE, sha256 TEXT NOT NULL, byte_size INTEGER NOT NULL);
CREATE TABLE learning_enrollments(id TEXT PRIMARY KEY, person_id TEXT NOT NULL REFERENCES people(id), knowledge_point_id TEXT NOT NULL REFERENCES knowledge_points(id), reason TEXT NOT NULL, enrolled_on TEXT, source_event_id TEXT, UNIQUE(person_id,knowledge_point_id));
CREATE TABLE study_plan_items(id TEXT PRIMARY KEY, person_id TEXT NOT NULL REFERENCES people(id), knowledge_point_id TEXT REFERENCES knowledge_points(id), kind TEXT NOT NULL, planned_on TEXT, status TEXT NOT NULL, reason TEXT NOT NULL);
CREATE TABLE scheduler_configs(version TEXT PRIMARY KEY, name TEXT NOT NULL, parameters_json TEXT NOT NULL, historical_version_known INTEGER NOT NULL);
CREATE TABLE review_states(person_id TEXT NOT NULL REFERENCES people(id), knowledge_point_id TEXT NOT NULL REFERENCES knowledge_points(id), stage TEXT, interval_days INTEGER, next_review_on TEXT, last_reviewed_on TEXT, last_rating TEXT, pending_forgotten INTEGER NOT NULL, scheduler_version TEXT REFERENCES scheduler_configs(version), historical_scheduler_version TEXT, snapshot_json TEXT NOT NULL, PRIMARY KEY(person_id,knowledge_point_id));
CREATE INDEX review_states_due ON review_states(person_id,next_review_on);
CREATE TABLE learning_events(id TEXT PRIMARY KEY, person_id TEXT NOT NULL REFERENCES people(id), knowledge_point_id TEXT REFERENCES knowledge_points(id), event_type TEXT NOT NULL, on_date TEXT, recorded_at TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE review_logs(id TEXT PRIMARY KEY, person_id TEXT NOT NULL REFERENCES people(id), knowledge_point_id TEXT NOT NULL REFERENCES knowledge_points(id), rating TEXT, reviewed_on TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE answer_attempts(id TEXT PRIMARY KEY, person_id TEXT NOT NULL REFERENCES people(id), knowledge_point_id TEXT REFERENCES knowledge_points(id), answer_text TEXT, created_at TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE answer_feedbacks(id TEXT PRIMARY KEY, attempt_id TEXT REFERENCES answer_attempts(id), status TEXT, created_at TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE reference_answers(id TEXT PRIMARY KEY, knowledge_point_id TEXT NOT NULL REFERENCES knowledge_points(id), status TEXT, current_version INTEGER, snapshot_json TEXT NOT NULL);
CREATE TABLE reference_answer_versions(id TEXT PRIMARY KEY, answer_id TEXT NOT NULL REFERENCES reference_answers(id), version INTEGER NOT NULL, snapshot_json TEXT NOT NULL);
CREATE TABLE practice_sessions(id TEXT PRIMARY KEY, person_id TEXT NOT NULL REFERENCES people(id), knowledge_point_id TEXT REFERENCES knowledge_points(id), status TEXT, created_at TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE task_completion_logs(id TEXT PRIMARY KEY, person_id TEXT NOT NULL REFERENCES people(id), reported_on TEXT, content TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE processing_jobs(id TEXT PRIMARY KEY, scope_id TEXT REFERENCES conversation_scopes(id), session_id TEXT REFERENCES conversation_sessions(id), job_type TEXT NOT NULL, status TEXT, created_at TEXT, source_message_id TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE job_events(id TEXT PRIMARY KEY, job_id TEXT REFERENCES processing_jobs(id), event_type TEXT NOT NULL, occurred_at TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE draft_versions(id TEXT PRIMARY KEY, job_id TEXT NOT NULL REFERENCES processing_jobs(id), version INTEGER NOT NULL, snapshot_json TEXT NOT NULL);
CREATE TABLE context_usage_events(id TEXT PRIMARY KEY, reply_event_id TEXT REFERENCES conversation_events(id), scope_id TEXT REFERENCES conversation_scopes(id), captured_at TEXT NOT NULL, snapshot_json TEXT NOT NULL);
CREATE TABLE channel_records(id TEXT PRIMARY KEY, record_type TEXT NOT NULL, scope_key TEXT, source_key TEXT, snapshot_json TEXT NOT NULL);
CREATE TABLE migration_inventory(source_path TEXT PRIMARY KEY, target_table TEXT NOT NULL, target_id TEXT NOT NULL, source_sha256 TEXT NOT NULL, UNIQUE(target_table,target_id));
CREATE TABLE migration_metadata(key TEXT PRIMARY KEY, value_json TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS upload_transcriptions(job_id TEXT PRIMARY KEY REFERENCES processing_jobs(id),title TEXT NOT NULL,version INTEGER NOT NULL,updated_at TEXT,items_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS upload_transcription_versions(job_id TEXT NOT NULL REFERENCES processing_jobs(id),version INTEGER NOT NULL,title TEXT NOT NULL,edited_at TEXT NOT NULL,actor TEXT NOT NULL,items_json TEXT NOT NULL,PRIMARY KEY(job_id,version));

CREATE TABLE IF NOT EXISTS runtime_fragments(path TEXT PRIMARY KEY,value_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS migration_originals(source_path TEXT PRIMARY KEY,snapshot_json TEXT NOT NULL);
