const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const envs={prod:'正式环境',test:'测试环境',local:'本地验证',all:'全部环境'};
const purposes={chat:'模型回复',intent:'意图识别',coaching:'辅导',feedback:'答题反馈',photo:'图片整理',verification:'联网核验',ocr:'图片识读',alignment:'合并整理',revision:'资料修订'};
const statuses={success:'完成',failed:'失败',timeout:'超时',running:'处理中',interrupted:'中断'};
const money=n=>n===null?'待核实':new Intl.NumberFormat('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n/1e9);
const number=n=>new Intl.NumberFormat('zh-CN').format(n||0);
const state={environment:'prod',period:'month',page:1,purpose:'all',status:'all',q:new URLSearchParams(location.search).get('q')||'',view:'overview'};let data;
async function api(path,body){const r=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(r.status===401){location.replace('/login');throw new Error('登录已过期');}const v=await r.json();if(!r.ok)throw new Error(v.error||'请求失败');return v;}
const params=()=>new URLSearchParams(state).toString();
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
async function load(){data=await api('/api/console/costs?'+params());render();}
function metrics(){const s=data.summary;$('#metrics').innerHTML=[['模型估算费用','¥'+money(s.nanoCost),`${envs[data.environment]} · ${s.unpriced} 次请求待定价`,'dark'],['已观测 token',number(s.tokens),`输入 ${number(s.input)} · 输出 ${number(s.output)}`,''],['官方已结算','—','按账单指定范围查看',''],['用量待核实',`${s.unknown} 笔`,`${s.count} 次请求 · ${s.running} 次处理中`,'alert-metric']].map(([label,value,note,cls])=>`<article class="metric ${cls}"><div class="metric-label">${label}</div><div class="metric-number">${value}</div><div class="metric-note">${note}</div></article>`).join('');
 const b=data.budget;$('#budget-alert').innerHTML=data.alerts.length?'<div class="budget-alert"><strong>正式环境已接近或超出参考预算</strong><span class="badge orange">继续调用</span></div>':'';
 $('#budget-summary').innerHTML=`<div class="budget-amount"><strong>${b.monthly?'¥'+b.monthly.toFixed(2):'未设置'}</strong></div><p class="panel-footnote">每月参考预算 · 每日 ${b.daily?'¥'+b.daily.toFixed(2):'未设置'}</p>`;}
function trend(){const days=data.days,max=Math.max(1,...days.map(d=>d.nanoCost/1e9));const xy=(d,i)=>[45+(days.length>1?510*i/(days.length-1):255),150-d.nanoCost/1e9/max*115];$('#trend-range').textContent=`${days[0]?.date||''} — ${data.today}`;
 $('#trend-chart').innerHTML=`<svg viewBox="0 0 600 170" role="img" aria-label="每日模型费用"><line x1="45" y1="150" x2="570" y2="150" stroke="#dce7ef"/><polyline fill="none" stroke="#397b9e" stroke-width="2" points="${days.map((d,i)=>xy(d,i).join(',')).join(' ')}"/>${days.map((d,i)=>{const [x,y]=xy(d,i);return `<circle cx="${x}" cy="${y}" r="4" fill="#397b9e"><title>${d.date} ¥${money(d.nanoCost)}</title></circle>`;}).join('')}</svg>`;
 $('#chart-days').innerHTML=days.filter((_,i)=>days.length<9||i%5===0||i===days.length-1).map(d=>`<span data-date="${d.date}">${d.date.slice(5)}</span>`).join('');}
function overview(){trend();$('#purpose-breakdown').innerHTML=data.purposes.length?`<div class="purpose-list">${data.purposes.map(p=>`<div class="purpose-row"><div class="purpose-title"><strong>${esc(purposes[p.purpose]||p.purpose)}</strong><span>¥${money(p.nanoCost)}</span></div><progress class="purpose-track" max="100" value="${data.summary.nanoCost?p.nanoCost/data.summary.nanoCost*100:0}"></progress><div class="purpose-sub">${p.count} 次请求</div></div>`).join('')}</div>`:'<div class="empty-state">尚无请求记录</div>';
 $('#top-tasks').innerHTML=data.tasks.length?data.tasks.slice(0,4).map(t=>`<button class="task-row" data-task="${esc(t.id)}"><span class="task-glyph">图</span><span><strong class="task-title">${esc(t.title)}</strong><small class="task-meta">${t.count} 次请求 · ${t.unknown} 笔待核实</small></span><span class="task-cost">¥${money(t.nanoCost)}</span><span>↗</span></button>`).join(''):'<div class="empty-state">尚无任务记录</div>';
 $('#task-scope-note').textContent='显示所选范围内费用较高的任务';}
function requests(){const rows=data.requests;$('#request-rows').innerHTML=rows.length?rows.map(r=>`<tr><td>${esc(new Date(r.startedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}))}<small>${esc(r.id)}</small></td><td>${esc(r.title)}<small>${esc(purposes[r.purpose]||r.purpose)}</small></td><td>${esc(envs[r.environment]||r.environment)}<small>${esc(r.key)}</small></td><td>${r.input===null?'未知':number(r.input)} / ${r.output===null?'未知':number(r.output)}<small>其中推理 ${r.reasoning===null?'未知':number(r.reasoning)}</small></td><td>${r.nanoCost===null?'待核实':'¥'+money(r.nanoCost)}<small>${r.toolCostUnknown?'工具费待核对':''}</small></td><td><span class="badge">${esc(r.businessStatus==='parse_failed'?'格式校验失败':statuses[r.status]||r.status)}</span></td><td><button class="text-button" data-request="${esc(r.id)}">详情 ↗</button></td></tr>`).join(''):'<tr><td colspan="7"><div class="empty-state">没有匹配的请求</div></td></tr>';
 $('#request-pagination').innerHTML=`<span>${data.total} 条 · ${data.page} / ${data.pages} 页</span><div class="pagination"><button id="prev" ${data.page===1?'disabled':''}>‹</button><button id="next" ${data.page===data.pages?'disabled':''}>›</button></div>`;}
function statement(){const rows=data.statements;$('#clear-statement').hidden=false;$('#statement-content').innerHTML=rows.length?rows.map(s=>`<div class="statement-intro"><strong>${esc(envs[s.environment])} · ${esc(s.key)} · ${esc(s.billingItem)}</strong><br>${esc(s.from)} — ${esc(s.to)} · 导入 ${esc(new Date(s.createdAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}))}</div><div class="statement-metrics"><div class="statement-metric"><span>同范围本地模型估算</span><strong>¥${money(s.local.nanoCost)}</strong><small>${s.local.unknown} 笔未知用量</small></div><div class="statement-metric"><span>官方用量</span><strong>${number(s.tokens)}</strong><small>与本地差额 ${number(s.tokens-s.local.tokens)} token</small></div><div class="statement-metric"><span>官方结算实扣</span><strong>¥${s.paidYuan.toFixed(2)}</strong><small>${esc(s.sourceName)}</small></div></div>`).join(''):'<div class="statement-empty"><h3>未同步账单</h3></div>';
 $('#key-content').innerHTML=`<div class="table-scroll"><table><thead><tr><th>Key 别名</th><th>环境</th><th>资源 ID</th></tr></thead><tbody>${data.keys.map(k=>`<tr><td>${esc(k.alias)}</td><td>${esc(envs[k.environment])}</td><td>${esc(k.resourceId||'未关联')}</td></tr>`).join('')}</tbody></table></div><button id="edit-prices" class="text-button">模型价目</button>`;}
function render(){metrics();overview();requests();statement();route();}
function route(){state.view=['overview','requests','reconciliation'].includes(location.hash.slice(1))?location.hash.slice(1):'overview';document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==state.view+'-view');document.querySelectorAll('[data-view]').forEach(a=>a.classList.toggle('active',a.dataset.view===state.view));}
function requestDetail(r){return `<div class="detail-context"><p>${esc(r.title)} · ${esc(purposes[r.purpose]||r.purpose)}</p><p>请求 ${esc(r.id)}<br>任务 ${esc(r.taskId)}<br>${esc(r.api)} · ${esc(r.model)}<br>${esc(r.environment)} · ${esc(r.key)}<br>状态 ${esc(r.status)} / ${esc(r.businessStatus)}<br>步骤 ${esc(r.step||'回复与思考')}<br>响应 ${esc(r.responseId||'未取得')}</p></div><div class="request-breakdown"><dl>${[['总输入',r.input],['其中缓存',r.cached],['总输出',r.output],['其中推理',r.reasoning]].map(([k,v])=>`<dt>${k}</dt><dd>${v===null?'未知':number(v)}</dd>`).join('')}<dt>模型估算</dt><dd>${r.nanoCost===null?'待核实':'¥'+(r.nanoCost/1e9).toFixed(6)}</dd><dt>采用价目</dt><dd>${esc(r.priceVersion||'未定价')}</dd></dl><p class="detail-footnote">缓存包含在输入中，推理包含在输出中。${r.toolCostUnknown?'另有工具费用待核对。':''}</p></div>`;}
async function detail(kind,id){const value=await api(`/api/console/costs/${kind}/${encodeURIComponent(id)}`);$('#detail-title').textContent=kind==='tasks'?'任务调用详情':'请求详情';$('#detail-content').innerHTML=Array.isArray(value)?value.map(requestDetail).join(''):requestDetail(value);$('#detail-dialog').showModal();}
function budget(){const b=data.budget;$('#monthly-budget').value=b.monthly??'';$('#daily-budget').value=b.daily??'';$('#budget-dialog').showModal();}
$('#budget-form').addEventListener('submit',async e=>{e.preventDefault();try{await api('/api/console/costs/budget',{daily:$('#daily-budget').value?Number($('#daily-budget').value):null,monthly:$('#monthly-budget').value?Number($('#monthly-budget').value):null});$('#budget-dialog').close();await load();toast('预算已保存，超额继续调用');}catch(e){toast(e.message);}});
$('#edit-budget').onclick=budget;$('#edit-budget-secondary').onclick=budget;
for(const id of ['close-budget','cancel-budget'])$('#'+id).onclick=()=>$('#budget-dialog').close();$('#close-detail').onclick=()=>$('#detail-dialog').close();
$('#environment').onchange=async e=>{state.environment=e.target.value;state.page=1;await load();};
document.querySelectorAll('[data-period]').forEach(b=>b.onclick=async()=>{state.period=b.dataset.period;state.page=1;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));await load();});
$('#purpose-filter').innerHTML='<option value="all">全部用途</option>'+Object.entries(purposes).map(([id,name])=>`<option value="${id}">${name}</option>`).join('');
for(const [id,key] of [['purpose-filter','purpose'],['status-filter','status']])$('#'+id).onchange=async e=>{state[key]=e.target.value;state.page=1;await load();};
$('#request-search').oninput=e=>{state.q=e.target.value;state.page=1;clearTimeout(load.timer);load.timer=setTimeout(()=>load().catch(e=>toast(e.message)),250);};
$('#reset-filters').onclick=async()=>{state.q='';state.purpose='all';state.status='all';state.page=1;$('#request-search').value='';$('#purpose-filter').value='all';$('#status-filter').value='all';await load();};
$('#show-all').onclick=()=>location.hash='requests';$('#export-csv').onclick=()=>{const a=document.createElement('a');a.href='/api/console/costs/export.csv?'+params();a.download='333-model-costs.csv';document.body.append(a);a.click();a.remove();};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const action=b.dataset.task?detail('tasks',b.dataset.task):b.dataset.request?detail('requests',b.dataset.request):b.id==='prev'||b.id==='next'?(state.page+=b.id==='next'?1:-1,load()):null;action?.catch(e=>toast(e.message));});
$('#clear-statement').onclick=()=>toast('导入官方 CSV 或 JSON，确认 Key、日期、用量和实扣列。官方汇总不再次加入请求账本。');
$('#load-statement').onclick=()=>importFile();
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(Boolean))rows.push(row);if(quoted)throw new Error('CSV 引号不完整');return rows;}
async function importFile(){const chooser=document.createElement('input');chooser.type='file';chooser.id='statement-file';chooser.accept='.csv,.json';chooser.hidden=true;document.querySelector('#statement-file')?.remove();document.body.append(chooser);chooser.onchange=async()=>{try{const file=chooser.files[0];if(!file)return;if(file.size>1000000)throw new Error('账单文件过大，请分批导出');const text=(await file.text()).replace(/^\uFEFF/,'');const sourceHash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text)))).map(n=>n.toString(16).padStart(2,'0')).join('');if(file.name.endsWith('.json')){const input={...JSON.parse(text),sourceName:file.name,sourceHash};return await confirmStatement(input);}
 const rows=parseCsv(text),headers=rows.shift();if(!rows.length)throw new Error('账单没有数据行');const opts=headers.map((h,i)=>`<option value="${i}">${esc(h)}</option>`).join('');
 $('#detail-title').textContent='账单列映射';$('#detail-content').innerHTML=`<form id="statement-form" class="request-breakdown"><p>${esc(file.name)} · ${rows.length} 行</p><label>环境<select name="environment">${Object.entries(envs).filter(([k])=>k!=='all').map(([k,n])=>`<option value="${k}">${n}</option>`).join('')}</select></label><p><label>Key 别名<input name="key" required></label></p><p><label>起始日期<input name="from" type="date" required></label> <label>结束日期<input name="to" type="date" required></label></p><p><label>总 token 列<select name="tokens">${opts}</select></label></p><p><label>实扣金额列（元）<select name="paid">${opts}</select></label></p><p>文件应已按选定 Key、日期与模型推理费用导出。</p><button class="button primary">预览导入</button></form>`;$('#detail-dialog').showModal();$('#statement-form').onsubmit=async e=>{e.preventDefault();try{const f=new FormData(e.target);const sum=column=>rows.reduce((n,r)=>{const v=Number(String(r[column]||'').replaceAll(',',''));if(!Number.isFinite(v)||v<0)throw new Error('选定列包含无效数字');return n+v;},0);const input={environment:f.get('environment'),key:f.get('key'),from:f.get('from'),to:f.get('to'),tokens:sum(Number(f.get('tokens'))),paidYuan:sum(Number(f.get('paid'))),sourceName:file.name,sourceHash};$('#detail-dialog').close();await confirmStatement(input);}catch(e){toast(e.message);}};
 }catch(e){toast(e.message);}};chooser.click();}
async function confirmStatement(input){const v=await api('/api/console/costs/statements?preview=true',input);$('#detail-title').textContent='账单导入预览';$('#detail-content').innerHTML=`<div class="request-breakdown"><p>${esc(v.key)} · ${esc(v.environment)} · ${esc(v.from)} — ${esc(v.to)}</p><p>官方 ${number(v.tokens)} token · 实扣 ¥${v.paidYuan.toFixed(2)}</p><p>本地 ${number(v.local.tokens)} token · 估算 ¥${money(v.local.nanoCost)}</p><button class="button primary" id="save-statement">确认导入</button></div>`;$('#detail-dialog').showModal();$('#save-statement').onclick=async()=>{try{await api('/api/console/costs/statements',input);$('#detail-dialog').close();await load();toast('账单已导入');}catch(e){toast(e.message);}};}
document.addEventListener('click',e=>{if(e.target.id!=='edit-prices')return;$('#detail-title').textContent='模型价目';$('#detail-content').innerHTML='<div class="request-breakdown">'+data.prices.map(p=>'<p>'+esc(p.model)+' · '+esc(p.tier)+'<br>每百万 token：输入 '+p.input+' 元 · 缓存 '+p.cached+' 元 · 输出 '+p.output+' 元<br>生效 '+esc(p.effectiveFrom)+'</p>').join('')+'<form id="price-form"><label>新价目 JSON<textarea id="price-json" rows="7" required></textarea></label><button class="button primary">保存新版本</button></form></div>';$('#price-json').value=JSON.stringify({model:'doubao-seed-2-1-pro-260915',tier:'default',input:6,cached:1.2,output:30,effectiveFrom:new Date().toISOString(),source:'https://docs.volcengine.com/docs/ark/model-pricing?lang=zh'},null,2);$('#detail-dialog').showModal();$('#price-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/console/costs/prices',JSON.parse($('#price-json').value));$('#detail-dialog').close();await load();toast('新价目已保存，历史请求保持原价目');}catch(error){toast(error.message);}};});
document.querySelector('#request-search').value=state.q;window.addEventListener('hashchange',route);load().catch(e=>toast(e.message));
