const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,body){const r=await fetch(path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const v=await r.json();if(!r.ok)throw new Error(v.error||'请求失败');return v;}
const at=v=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'}):'历史时间未记录';
const rating=r=>({again:'没想起来',hard:'很吃力',good:'基本掌握',easy:'很熟练'}[r]||'未自评');
export async function mountManagementPage(page,{drawer,toast}) {
  const main=document.querySelector('#main');
  if(page==='review-records'){
    main.innerHTML='<section class="page-heading"><h1>复习记录</h1><input id="review-month" type="month"><a class="button" href="/calendar.html">复习日历 ↗</a></section><section class="panel"><div id="review-list">正在读取…</div></section>';
    const month=document.querySelector('#review-month');month.value=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit'}).format(new Date());
    const load=async()=>{const d=await api('/api/console/review-records?month='+month.value);document.querySelector('#review-list').innerHTML=`<div class="panel-heading"><h2>${d.records.length} 次真实自评 · ${d.attempts.length} 份作答 · ${d.opened.length} 次打开</h2></div><div class="table-scroll"><table><thead><tr><th>日期 / 知识点</th><th>自评</th><th>反馈</th><th>当次下次日期</th><th></th></tr></thead><tbody>${d.records.map(r=>`<tr><td>${esc(r.reviewedOn)}<br>${esc(r.title)}</td><td>${rating(r.rating)}</td><td>${r.feedback.map(f=>esc(f.status)).join('、')||'未关联'}</td><td>${esc(r.nextReviewOn||'未知')}</td><td><button class="text-button" data-review="${esc(r.id)}">详情 ↗</button></td></tr>`).join('')}</tbody></table></div><div class="panel-heading"><h2>已保存答案</h2></div>${d.attempts.map(a=>`<button class="task" data-answer="${esc(a.id)}">${esc(a.title)} · ${a.reviewId?'已自评':'未关联自评'} · ${at(a.submittedAt)}</button>`).join('')||'<p class="empty">暂无记录</p>'}`;
      document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{const r=d.records.find(r=>r.id===b.dataset.review);drawer('复习详情',`<h2>${esc(r.title)}</h2><p>自评 ${rating(r.rating)} · ${at(r.reviewedAt)}</p><p>当次下次日期 ${esc(r.nextReviewOn||'未知')}<br>当前排程 ${esc(r.currentState?.nextReviewOn||'未知')}</p>${answerDetail(r.attempt,r.feedback)}<p>自评 ID ${esc(r.id)}<br>关联来源 ${esc(r.sourceId||'未记录')}</p>`);});
      document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const a=d.attempts.find(a=>a.id===b.dataset.answer);drawer('作答详情',`<h2>${esc(a.title)}</h2>${answerDetail(a,a.feedback)}`);});
    };month.onchange=()=>load().catch(e=>toast(e.message));await load();return;
  }
  const operations=await api('/api/console/operations');
  main.innerHTML=`<section class="page-heading"><h1>管理操作</h1><button class="button" id="new-operation">发送群消息</button><button class="button" id="record-operation">登记已执行操作</button></section><section class="panel"><div class="table-scroll"><table><thead><tr><th>时间</th><th>操作</th><th>执行方式</th><th>状态</th><th></th></tr></thead><tbody>${operations.map(o=>`<tr><td>${at(o.occurredAt||o.createdAt)}</td><td>${esc(o.summary)}<br>${esc(o.chatName||o.chatId||'外部操作')}</td><td>${esc(o.executionSource)}</td><td>${esc(o.status)}</td><td><button class="text-button" data-operation="${o.id}">详情 ↗</button></td></tr>`).join('')}</tbody></table></div>${operations.length?'':'<p class="empty">暂无操作记录</p>'}</section>`;
  document.querySelectorAll('[data-operation]').forEach(b=>b.onclick=()=>{const o=operations.find(o=>o.id===b.dataset.operation);drawer('管理操作详情',`<h2>${esc(o.summary)}</h2><p>${esc(o.status)} · ${esc(o.executionSource)} · ${esc(o.actorId)}</p><div class="source-text">${esc(o.text||o.publicText||'')}</div><p>回执 ${esc(o.messageId||'未取得')}<br>执行 ${at(o.occurredAt)}<br>记录 ${at(o.recordedAt||o.createdAt)}</p><div class="source-text">${esc(o.evidence||'')}</div>${o.kind==='send'?'<form id="reconcile-form"><label>核实消息 ID<input name="messageId" placeholder="om_…" required></label><button class="button">读取真实回执</button></form>':''}`);const form=document.querySelector('#reconcile-form');if(form)form.onsubmit=async e=>{e.preventDefault();try{await api(`/api/console/operations/${o.id}/reconcile`,Object.fromEntries(new FormData(form)));document.querySelector('#detail').close();await mountManagementPage(page,{drawer,toast});}catch(e){toast(e.message);}};});
  document.querySelector('#new-operation').onclick=()=>{drawer('发送群消息','<h2>发送群消息</h2><form id="send-form"><p><label>目标群 ID<input name="chatId" placeholder="oc_…" required></label></p><p><label>@ 账号（逗号分隔）<input name="mentions" placeholder="ou_…"></label></p><p><label>操作摘要<input name="summary" required></label></p><label>正文<textarea name="text" rows="7" required></textarea></label><button class="button">预览目标与正文</button></form>');const form=document.querySelector('#send-form');form.onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(form));const input={...f,mentions:f.mentions.split(',').map(s=>s.trim()).filter(Boolean),requestId:crypto.randomUUID()};try{const p=await api('/api/console/operations/preview',input);drawer('发送预览',`<h2>${esc(p.chatName)}</h2><p>${esc(p.chatId)}</p><div class="source-text">${esc(p.text)}</div><button id="execute-send" class="button">发送</button>`);document.querySelector('#execute-send').onclick=async e=>{e.target.disabled=true;try{const result=await api('/api/console/operations/send',input);toast(result.status==='sent'?'已发送':'结果待核实，不自动重发');document.querySelector('#detail').close();await mountManagementPage(page,{drawer,toast});}catch(e){toast(e.message);}};}catch(e){toast(e.message);}};};
  document.querySelector('#record-operation').onclick=()=>{drawer('登记已执行操作','<h2>登记已执行操作</h2><form id="record-form"><p><label>实际执行时间（北京时间）<input name="occurredAt" type="datetime-local" required></label></p><p><label>执行方式<input name="executionSource" value="codex" required></label></p><p><label>目标群 ID（可空）<input name="chatId"></label></p><p><label>管理摘要<textarea name="summary" rows="3" required></textarea></label></p><p><label>可进入群上下文的结果<textarea name="publicText" rows="3"></textarea></label></p><p><label>证据<textarea name="evidence" rows="3"></textarea></label></p><button class="button">保存记录</button></form>');const form=document.querySelector('#record-form');form.onsubmit=async e=>{e.preventDefault();const input=Object.fromEntries(new FormData(form));input.requestId=crypto.randomUUID();input.occurredAt=new Date(input.occurredAt+'+08:00').toISOString();try{await api('/api/console/operations/record',input);document.querySelector('#detail').close();await mountManagementPage(page,{drawer,toast});toast('已登记，不执行新操作');}catch(e){toast(e.message);}};};
}
function answerDetail(a,feedback=[]){return a?`<p>作答 ${at(a.submittedAt)}<br>作答 ID ${esc(a.id)}<br>练习 ${esc(a.practiceSessionId||'未记录')}<br>材料版本 ${esc(a.taskSnapshot?.reference?.sourceVersion||a.taskSnapshot?.reference?.answer?.version||'未记录')}</p><h3>本人原始答案</h3><div class="source-text">${esc(a.content)}</div><h3>当时题目</h3><div class="source-text">${esc(a.taskSnapshot?.prompt||'未记录')}</div><h3>模型反馈</h3>${feedback.map(f=>`<p>${esc(f.status)}</p><div class="source-text">${esc(f.feedback||f.errorCode||'处理中或未返回')}</div>${f.jobId?'<p><a href="/console/cost/?q='+encodeURIComponent(f.jobId)+'#requests">查看本次反馈的模型请求与费用 ↗</a></p>':''}`).join('')||'<p>未关联反馈</p>'}`:'<p>历史作答未能精确关联</p>';}
